services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VIRTUALHOST}
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  identity:
    build:
      context: ./src
      dockerfile: Ims.DemoPlatform.Identity.API/Dockerfile
    container_name: identity
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQOptions__Host=rabbitmq
      - RabbitMQOptions__Exchange=auth.events
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};Include Error Detail=true
      - Cors__AllowedOrigins__0=${CORS_ALLOWED_ORIGIN}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__SigningKey=${JWT_SIGNING_KEY}
      - Jwt__AccessTokenMinutes=${JWT_ACCESS_TOKEN_MINUTES}
      - Jwt__RefreshTokenDays=${JWT_REFRESH_TOKEN_DAYS}
    ports:
      - "5006:8080"
    volumes:
      - ./logs:/logs


  notifications:
    build:
      context: ./src
      dockerfile: Ims.DemoPlatform.NotificationsService/Dockerfile
    container_name: notifications
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQOptions__Host=${RABBITMQ_HOST}
      - RabbitMQOptions__Exchange=${RABBITMQ_EXCHANGE}
      - SmtpOptions__Host=${SMTP_HOST}
      - SmtpOptions__Port=${SMTP_PORT}
      - SmtpOptions__Name=${SMTP_NAME}
      - SmtpOptions__User=${SMTP_USER}
      - SmtpOptions__Password=${SMTP_PASSWORD}
      - SmtpOptions__EnableSsl=${SMTP_ENABLE_SSL}
    volumes:
      - ./logs:/logs

  projects:
    build:
      context: ./src
      dockerfile: Ims.DemoPlatform.Projects.API/Dockerfile
    container_name: projects
    depends_on:
      - identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Port=${DB_PORT};Database=${PROJECT_DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};Include Error Detail=true
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__SigningKey=${JWT_SIGNING_KEY}
      - Jwt__AccessTokenMinutes=${JWT_ACCESS_TOKEN_MINUTES}
      - Jwt__RefreshTokenDays=${JWT_REFRESH_TOKEN_DAYS}
      - Cors__AllowedOrigins__0=${CORS_ALLOWED_ORIGIN}
    ports:
      - "5007:8080"
    volumes:
      - ./logs:/logs

  tasks:
    build:
      context: ./src
      dockerfile: Ims.DemoPlatform.Tasks.API/Dockerfile
    container_name: tasks
    depends_on:
      - identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Port=${DB_PORT};Database=${TASK_DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};Include Error Detail=true
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__SigningKey=${JWT_SIGNING_KEY}
      - Jwt__AccessTokenMinutes=${JWT_ACCESS_TOKEN_MINUTES}
      - Jwt__RefreshTokenDays=${JWT_REFRESH_TOKEN_DAYS}
      - Cors__AllowedOrigins__0=${CORS_ALLOWED_ORIGIN}
    ports:
      - "5008:8080"
    volumes:
      - ./logs:/logs

  gateway:
    build:
      context: ./src
      dockerfile: Ims.DemoPlatform.Gateway.API/Dockerfile
    container_name: gateway
    depends_on:
      - identity
      - notifications
      - projects
      - tasks
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
    volumes:
      - ./logs:/logs

#  web:
#    build:
#      context: ./web-client
#      dockerfile: Dockerfile
#    container_name: web-client
#    ports:
#      - "5173:5173"
#    environment:
#      - VITE_AUTH_API_BASE=${VITE_AUTH_API_BASE}
#    depends_on:
#      - identity

