// <auto-generated />
using System;
using Ims.DemoPlatform.Tasks.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ims.DemoPlatform.Tasks.API.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    partial class TaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ims.DemoPlatform.Tasks.API.Models.Entities.ProjectTask", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid");
                    b.Property<Guid?>("AssignedUserId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").HasMaxLength(2000).HasColumnType("character varying(2000)");
                    b.Property<Guid>("ProjectId").HasColumnType("uuid");
                    b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.HasKey("Id");
                    b.HasIndex("AssignedUserId");
                    b.HasIndex("ProjectId");
                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}

