// <auto-generated />
using System;
using Ims.DemoPlatform.Projects.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ims.DemoPlatform.Projects.API.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ims.DemoPlatform.Projects.API.Models.Entities.Project", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<Guid>("OwnerId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}

