name: .NET CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DOTNET_VERSION: "9.0.x"
  CONFIGURATION: Release
  SOLUTION_FILE: ./Ims.DemoPlatform.sln

jobs:
  test:
    name: Build & Test (.NET solution)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET (global.json)
        if: ${{ hashFiles('global.json') != '' }}
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Setup .NET (fallback)
        if: ${{ hashFiles('global.json') == '' }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: |
            **/*.csproj
            global.json

      - name: Restore (solution)
        run: dotnet restore "$SOLUTION_FILE"

      - name: Build (solution)
        run: dotnet build "$SOLUTION_FILE" --no-restore -c "$CONFIGURATION"

      - name: Test (solution if tests exist)
        shell: bash
        run: |
          if find . -name "*Tests.csproj" -print -quit | grep -q .; then
            dotnet test "$SOLUTION_FILE" --no-build -c "$CONFIGURATION" --logger "trx;LogFileName=tests.trx"
          else
            echo "No *Tests.csproj found — skipping test step."
          fi

      - name: Upload test results (TRX)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/*.trx
